config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :users, only: [:edit, :update]
  resources :routines, only: [:create] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :posts, only: [:index, :create, :destroy]
  resources :favorites, only: [:new, :create]
  resources :todos, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :routines
  has_many :favorites
  has_many :todos
  has_many :posts

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def new
    @favorite = Favorite.new
  end

  def create
    Favorite.create(favorite_params)
    redirect_to root_path
  end

  private
  def favorite_params
    params.require(:favorite).permit(:name, :rank, :image, :url).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    @post = Post.new
    @posts = Post.where(user: current_user.id).order('created_at ASC').includes(:user)

    @favorite = Favorite.new
    @favorites = Favorite.where(user: current_user.id).order('rank ASC').includes(:user)

    @todo = Todo.new
    @todos = Todo.where(user: current_user.id).order('created_at ASC').includes(:user)

    @routine = Routine.new
    @routines = Routine.where(user: current_user.id).group(:content).count
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def create
    for num in 1..routine_params[:turn].to_i do
      @routine = Routine.create(routine_params)
    end
    redirect_to root_path
  end

  def destroy_all
    Routine.destroy_all(['user_id = ?', current_user.id])
    redirect_to root_path
  end

  private
  def routine_params
    params.require(:routine).permit(:content, :turn).merge(user_id: current_user.id)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
    @todo = Todo.create(todo_params)
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { render json: @todo}
    end
  end

  def destroy
    post = Todo.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def todo_params
    params.require(:todo).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :image, :email, :twitter, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/_favorite.html.haml
%li.right-content__book__section__book-list__item
  = link_to favorite.url, target: :_blank do
    = image_tag favorite.image.url, class: 'right-content__book__section__book-list__item__image' if favorite.image.present?
    %p.right-content__book__section__book-list__item__rank
      = favorite.rank
      = "位"
    %h3.right-content__book__section__book-list__item__title
      = favorite.name

app/views/favorites/new.html.haml
.content__title
  新規アイテムの登録
= form_for @favorite, html: {class: 'favorite__form'} do |f|
  .right-content__post__form__box
    = f.text_field :name, class: 'favorite__form__box__test', placeholder: 'ここに名前を入力'
    = f.text_field :rank, class: 'favorite__form__box__test', placeholder: 'ここに数字を入力'
    = f.label :image, class: 'favorite__form__box__image-input' do
      = icon('fas', 'image', class: 'favorite__form__box__image-input--iconon')
      = f.file_field :image, class: 'favorite__form__box__image-input--hidden'
    = f.text_field :url, class: 'favorite__form__box', placeholder: 'ここにリンクを入力'
    = f.submit '登録', class: 'favorite__form__box__submit'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title SelfRealization
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/posts/_post.html.haml
%li.right-content__post__posts__list
  = post.content
  = image_tag post.image.url, class: 'right-content__post__posts__list__image' if post.image.present?
  .right-content__post__posts__list__date
    = post.created_at.strftime("%Y年%m月%d日")
    = link_to post_path(post.id), class: "right-content__todo__todos__box__list__btn--remove js-remove-btn", method: "delete" do
      削除

app/views/posts/index.html.haml
.wrapper
  .content
    .left-content
      .left-content__user
        %ul.left-content__user__lists
          %li.left-content__user__lists__list
            = current_user.name
          %li.left-content__user__lists__list
            = link_to current_user.twitter, class: "left-content__user__lists__list__twitter-btn" do
              = icon('fab', 'twitter')
              = "twitter"
          %li.left-content__user__lists__list
            = link_to "mailto:" + current_user.email, class: "left-content__user__lists__list__mail-btn" do
              = icon('far', 'envelope')
              = "mail"
          %li.left-content__user__lists__list
            = link_to edit_user_path(current_user), class: "left-content__user__lists__list__edit-btn" do
              = icon('fas', 'cog', class: 'icon')
              = "設定"
          %li.left-content__user__lists__list
            = link_to destroy_user_session_path, method: :delete, class: 'left-content__user__lists__list__out-btn' do
              = icon('fas', 'sign-out-alt', class: 'icon')
              = "ログアウト"
        = image_tag current_user.image, class: 'left-content__user__image'
        .left-content__user__content
          .left-content__user__title
            ＜自己紹介＞
          = current_user.content
      .left-content__time
        .left-content__time__chart
          ＜日々のルーティン＞
          - if Routine.exists?
            = link_to "全て削除", destroy_all_routines_path, method: :delete, class: "left-content__time__chart__delete--btn"
          = pie_chart @routines, id: "left-content__time__chart__routines" ,height: "280px", width: "400px"
          = form_for @routine, html: {class: 'left-content__time__chart__form'} do |f|
            = f.text_field :content, class: 'left-content__time__chart__form__text', placeholder: '勉強内容など自由に入力'
            - cnt = [["時間",""]]
            - for num in 1..24
              - cnt << num
            = f.select :turn, cnt, class: 'left-content__time__chart__form__cnt'
            = f.submit '登録', class: 'left-content__time__chart__form__submit'
        .left-content__time__calendar
          = month_calendar events: @posts do |date, posts|
            = date.day
            %ul.left-content__time__calendar__post--list
              - posts.each do |post|
                %li.left-content__time__calendar__post--list__content
                  = post.content
    .right-content
      .right-content__todo
        = form_for @todo, html: {class: 'right-content__todo__form'} do |f|
          = f.text_field :content, class: 'right-content__todo__form__text', placeholder: 'やらなければならないことToDoを入力'
          = f.submit '登録', class: 'right-content__todo__form__submit'
        .right-content__todo__title
          ＜ToDoリスト＞
        %ul.right-content__todo__todos
          = render @todos
      .right-content__book
        %section.right-content__book__section
          .right-content__book__section__menu
            ＜お気に入りの書籍＞
            -# = link_to new_favorite_path, class: "right-content__book__section__menu__new--btn" do
            -#   = icon('fas', 'pen-square', class: 'icon')
          %ul.right-content__book__section__book-list
            = render @favorites
          = form_for @favorite, html: {class: 'favorite__form'} do |f|
            .right-content__post__form__box
              - cnt = [["順位",""]]
              - for num in 1..36
                - cnt << num
              = f.select :rank, cnt, class: 'favorite__form__box__cnt'
              = f.text_field :name, class: 'favorite__form__box__text__name', placeholder: 'お気に入りの書籍名を入力'
              = f.label :image, class: 'favorite__form__box__image-input' do
                = icon('fas', 'image', class: 'favorite__form__box__image-input--iconon')
                = f.file_field :image, class: 'favorite__form__box__image-input--hidden'
            = f.text_field :url, class: 'favorite__form__box__text', placeholder: '購入リンクを入力'
            = f.submit '登録', class: 'favorite__form__submit'
      .right-content__post
        .right-content__post__title
          ＜毎日の積み上げ投稿＞
        %ul.right-content__post__posts
          = render @posts
        = form_for @post, html: {class: 'right-content__post__form'} do |f|
          .right-content__post__form__box
            != sprintf(f.date_select(:start_time, with_css_classes:'select-default_birthday', use_month_numbers: true,start_year: (Time.now.year), end_year: Time.now.year + 10, default: Date.new, date_separator:'%s'),'年','月')+'日'
            = f.text_field :content, class: 'right-content__post__form__box__text', placeholder: '今日の積み上げを入力'
            = f.label :image, class: 'right-content__post__form__box__image-input' do
              = icon('fas', 'image', class: 'right-content__post__form__box__image-input--iconon')
              = f.file_field :image, class: 'right-content__post__form__box__image-input--hidden'
          = f.submit '登録', class: 'right-content__post__form__submit'
  .footer
    .footer__small
      Copyright(C) Self Realization ALL RIGHTS RESERVED.

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view, class:"calendar-heading--link" %>
    <span class="calendar-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '翌月'), calendar.url_for_next_view, class:"calendar-heading--link" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/todos/_todo.html.haml
.right-content__todo__todos__box
  %li.right-content__todo__todos__box__list
    .right-content__todo__todos__box__list__title
      = todo.content
    = link_to todo_path(todo.id), class: "right-content__todo__todos__box__list__btn--remove js-remove-btn", method: "delete" do
      完了

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :twitter
          .field-input
            = f.text_field :twitter
        .field
          .field-label
            = f.label :content
          .field-input
            = f.text_field :content
        .field
          .field-label
            = f.label :image
          .field-input
            = f.text_field :image
            = f.file_field :image
        .actions
          = f.submit "Update", class: 'btn'